# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger/proto/messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessenger/proto/messenger.proto\x12\x08mes_grpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x0bSendRequest\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"<\n\x0cSendResponse\x12,\n\x08sendTime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"Z\n\x0cReadResponse\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12,\n\x08sendTime\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x91\x01\n\x0fMessengerServer\x12<\n\x0bSendMessage\x12\x15.mes_grpc.SendRequest\x1a\x16.mes_grpc.SendResponse\x12@\n\x0cReadMessages\x12\x16.google.protobuf.Empty\x1a\x16.mes_grpc.ReadResponse0\x01\x42\x11Z\x0fproto/;mes_grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messenger.proto.messenger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017proto/;mes_grpc'
  _globals['_SENDREQUEST']._serialized_start=107
  _globals['_SENDREQUEST']._serialized_end=150
  _globals['_SENDRESPONSE']._serialized_start=152
  _globals['_SENDRESPONSE']._serialized_end=212
  _globals['_READRESPONSE']._serialized_start=214
  _globals['_READRESPONSE']._serialized_end=304
  _globals['_MESSENGERSERVER']._serialized_start=307
  _globals['_MESSENGERSERVER']._serialized_end=452
# @@protoc_insertion_point(module_scope)
